server:
  port: 8103
security:
  user:
    name: eshop
    password: zhao
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
spring:
  application:
    name: eshop-price
  #  zipkin:
  #    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://192.168.100.54:3306/eshop
    username: root
    password: zhao
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql