server:
  port: 9411
spring:
  application:
    name: eshop-sleuth
security:
  user:
    name: eshop
    password: zhao
eureka:
  client:
    serviceUrl:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/