server:
  port: 8111
security:
  user:
    name: eshop
    password: zhao
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.100.54:3306/eshop
    username: root
    password: zhao
    driver-class-name: com.mysql.jdbc.Driver


