server:
  port: 8104
security:
  user:
    name: eshop
    password: zhao
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eshop-inventory