server:
  port: 8101
security:
  user:
    name: eshop
    password: zhao
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
spring:
  application:
    name: eshop-user
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://192.168.100.54:3306/eshop
    username: root
    password: zhao
#    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql