server:
  port: 8761

security:
  user:
    name: eshop
    password: zhao

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # 是否注册自身到eureka服务器
    fetchRegistry: false  # 是否从eureka服务器获取注册信息
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/   # 设置eureka服务器所在的地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   # 设置eureka服务器所在的地址
