server:
  port: 8080
security:
  user:
    name: eshop
    password: zhao
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
spring:
  application:
    name: eshop-gateway
zuul:
  routes:
    user:
      path: /user/**
      service-id: eshop-user
    product:
      path: /product/**
      service-id: eshop-product
    price:
      path: /price/**
      service-id: eshop-price
    inventory:
      path: /inventory/**
      service-id: eshop-inventory